[package]
name = "d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.47"

[[bin]]
name = "d"
path = "main.rs"
