[package]
name = "d1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
curl = "0.4.47"

[[bin]]
name = "d1"
path = "main.rs"
