[package]
name = "d12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.2"
curl = "0.4.47"

[[bin]]
name = "d12"
path = "main.rs"
